#!/usr/bin/env rake
# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)
  rake test                           # run tests normally

  rake test TESTOPTS="-v"             # run in verbose mode
  rake test TESTOPTS="--runner=fox"   # use the fox test runner
WebsitesPrototypeBuilder::Application.load_tasks
